### ISSUE TITLE
Basic Coin Generation

### ISSUE THREAD

**Issue by AV306** [nianny/furry-doodle-mod-attempt-2#4]
How are we going to get coins in-game?

Maybe wither an ore (weird) or mob drops?

@nianny

**Comment by AV306** [comment]
Loot chests!

Let's add to dungeon loot tables :D

**Comment by AV306** [comment]
wait shit i can't do that

**Comment by AV306** [comment]
let us generate random loot chests with hallocoins

**Comment by AV306** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by YeetBot3736** [comment]
you can technically jus override loottables

but hm wait for nianny to comment

**Comment by YeetBot3736** [comment]
*actl to add to loottables there's an event listener from fabric api

**Comment by AV306** [comment]
Adding to loot tables is a little overcomplicated, we could just make them craftable ig (which is what I did in the pr)

**Comment by nianny** [comment]
hm I was thinking of some kind of trading system
like you can trade in stuff like iron/gold/emeralds for hallo coins
then you can also trade in hallocoins for things like diamonds/netherite

and also hallo coin becomes like the main currency for a server
and honestly I have no idea how to prevent inflation from beeg farms

@AV306

**Comment by nianny** [comment]
hmmm maybe some kind of function to alter the exchange rate based on how many hallo coins there are in circulation

**Comment by nianny** [comment]
maybe some like of x square relationship maybee??? or maybe x (something more than 2)


so like hallo coin preserves its value

**Comment by nianny** [comment]
or maybe just let inflation happen (might mean one or two more higher level coins tho)

**Comment by AV306** [comment]
> hm I was thinking of some kind of trading system like you can trade in stuff like iron/gold/emeralds for hallo coins then you can also trade in hallocoins for things like diamonds/netherite
> 
> and also hallo coin becomes like the main currency for a server and honestly I have no idea how to prevent inflation from beeg farms
> 
> @AV306

wait then shouldn't this be like a plugin? this is more the scope of an economy plugin tbh
hm wait then hallocoins would be intangible
@nianny

**Comment by AV306** [comment]
> or maybe just let inflation happen (might mean one or two more higher level coins tho)

hm but we shouldn't bother about that its technically the problem of the people who play on the server
